welcome:
  message: Welcome to Solidarity
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springstudent
    url: jdbc:mysql://localhost:3306/task-app
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
